backend:
  secret:
    mongodb_uri:
      username: admin
      password: password
  ingress:
    enabled: false
frontend:
  ingress:
    enabled: false

ingress:
  hosts:
    - host:
        domain: client.mini.local
        chart: frontend
    - host:
        domain: api.mini.local
        chart: backend
