config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "api.mini.local/guestbook"
image:
  repository: phico/frontend
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: client.mini.local
