apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.name }}-{{ .Chart.name }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.name }}-{{ .Chart.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.name }}-{{ .Chart.name }}
    spec:
      containers:
      - image: {{ .Value.image.repository }}:{{ .Value.image.tag }}
        imagePullPolicy: Always
        name: {{ .Release.name }}-{{ .Chart.name }}
        ports:
        - name: {{ .Release.name }}-{{ .Chart.name }}
          containerPort: 4200
        env:
        - name: BACKEND_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.name }}-{{ .Chart.name }}-config
              key: backend-uri
        - name: GUESTBOOK_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.name }}-{{ .Chart.name }}-config
              key: guestbook-name


              

